name: CI - EventFlow Taller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Build simulado
        run: |
          echo "Ejecutando build simulado..."
          mkdir -p build

      - name: Test simulado
        run: |
          echo "Ejecutando tests simulados..."
          echo "Todos los tests han pasado (simulado)."

      - name: Copiar index.html a carpeta /build
        run: cp index.html build/

      - name: Mostrar archivos en /build
        run: ls -la build
